apiVersion: v1
kind: Service
metadata:
  name: semantic-search-service
spec:
  selector:
    app: semantic-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer